### ISSUE TITLE
단일 PDF 파일 만들기

### ISSUE THREAD

**Issue by Uni-** [Uni-/GGGGJ2016-Report#36]
예상 시나리오는 다음과 같습니다.

1. 이 GIt 저장소의 로컬 클론에서 작업빌드 스크립트는 위의 두 가지 작업을 모두 
2. GFM으로 이루어진 .md 파일들을 HTML로 렌더
3. A4 사이즈 PDF로 변환

2번 작업은 [Grip](https://pypi.python.org/pypi/grip)으로 가능합니다. Grip은 GitHub API를 이용해 GFM 파일을 HTML로 변환한 페이지를 제공하는 웹 서버 패키지입니다. 다만 Grip은 여러 Markdown 파일을 동시에 한 페이지의 HTML로 변환하는 방법은 제공하지 않습니다. (이슈를 제기했습니다만 바뀌기는 어려울 듯합니다. [이슈 링크](https://github.com/joeyespo/grip/issues/226)) 현 시점에서는 Grip의 `http://localhost:6419/`에 접속해서 HTML 페이지들을 하나로 병합하는 작업이 필요할 것 같습니다. 따라서 DOM 관련 라이브러리로 이 전처리를 할 별도의 프로그램을 작성할 필요가 있습니다.

3번 작업은 [cmdlnprint 확장](https://addons.mozilla.org/ko/firefox/addon/cmdlnprint/)을 설치한 Firefox로 가능합니다. cmdlnprint는 firefox 명령어에 `-print <url>` 옵션을 제공하며 이 결과로 Firefox는 `mozilla.pdf` 파일을 생성합니다. 매우 쉬운 방법입니다만 만약 출력 결과물의 퀄리티에 문제가 있다면, print mode HTML/CSS 해석과 PDF 변환에서 가장 좋은 결과를 내는 제품인 [Prince](http://www.princexml.com/)를 쓰는 방법도 있습니다. 이 작업도 2번 작업과 통합하여 하나의 프로그램으로 작성할 수 있을 것입니다.

**Comment by Perlmint** [comment]
https://github.com/Perlmint/grip-one 일단 grip api를 사용해서 하나의 HTML로 렌더링하는 간단한 스크립트 작성함.
PDF렌더링은 확인 안했으니 처리 필요함

**Comment by eonj** [comment]
보충기록: 단일 PDF 파일 생성하였고 각 동아리에 배포된 바 있음.

- File: [result.pdf](https://github.com/Uni-/GGGGJ2016-Report/files/3130260/result.pdf) (by @Perlmint)
- Checksum: SHA256 `ce93b6ee72ebb9fdb302004765aba7efd06526783f80ce10136e29f25fcfa3fa`

이슈 닫습니다.
